### PR TITLE
9.private-descriptor-template

### PR DESCRIPTION
**Pull request by geigerzaehler242**
Create private and public descriptors using descriptor templates

### CODE REVIEW

**Review by reez — APPROVED** [review]
LGTM!

Reviewed and ran locally.

**Comment by geigerzaehler242** [comment]
great. i have one more pr after this one gets merged

**Comment by thunderbiscuit** [comment]
@geigerzaehler242 can you rebase to pick up the latest changes? I'll merge this after.

**Comment by thunderbiscuit** [comment]
Nah don't close the PR! You can just rebase and force-push. Let us know if you need pointers to do that, happy to help.

**Pull request closed without merging**
