### PR TITLE
swift: add blockinfo and getaddress 

### PR DESCRIPTION
**Pull request by reez**
Adding the next two Swift files:

- [2.blockinfo.swift](https://github.com/thunderbiscuit/bitcoindevkit-scripts/commit/4595d673cdf41717b6f0901f19d0e2f3b7a32b9f)
- [3.getaddress.swift](https://github.com/thunderbiscuit/bitcoindevkit-scripts/commit/588cb148c2e90afdc6df7ac8e64e07b7cf6960a2)

**Styling**
Used existing Kotlin scripts format/styling converted to native Swift format/styling.

**Testing**
Tested and got no errors:

`swift sh 2.blockinfo.swift`
`Latest block is block 2423054 with hash 000000000000000834083d878f155374e83f9e85efec6c28f973048a1f6b234f`

`swift sh 3.getaddress.swift`
`The last unused address for this wallet is tb1qhtnymvqg47t7n9u8rc3nxrlg6mlut73yhevvvs at index 9`

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
Looks good thanks for the PR!

This is not an issue with this PR directly but I think we should look more into how to use the Swift tool we're using because for some reason it doesn't seem to pull the correct version defined in the file...

Swift Scripts

**Comment by thunderbiscuit** [comment]
I merged your PR but for some reason this PR says there is 1 commit left to merge? It also says that this commit introduces changes to 0 files... not sure what's up. But in any case I merged your stuff!

**Comment by thunderbiscuit** [comment]
Also I figured out how to pin the library version in a85a3717024ffd3b5c9818f91036cab67a8ab7d3.

We were using `https://github.com/bitcoindevkit/bdk-swift.git ~ 0.26.0` but we need to use `https://github.com/bitcoindevkit/bdk-swift.git == 0.26.0`

**Comment by reez** [comment]
> Also I figured out how to pin the library version in [a85a371](https://github.com/thunderbiscuit/bitcoindevkit-scripts/commit/a85a3717024ffd3b5c9818f91036cab67a8ab7d3).
> 
> We were using `https://github.com/bitcoindevkit/bdk-swift.git ~ 0.26.0` but we need to use `https://github.com/bitcoindevkit/bdk-swift.git == 0.26.0`

Awesome, good job figuring this out pretty quickly, nice!

**Comment by reez** [comment]
> I merged your PR but for some reason this PR says there is 1 commit left to merge? It also says that this commit introduces changes to 0 files... not sure what's up. But in any case I merged your stuff!

Wow that’s very weird indeed. Well feel free to close this PR if you want, it definitely looks like everything is merged in, and I’ve also got the local branch if ever needed. This week I’ll probably look into how this PR ended up in a weird state currently because I wonder how exactly that even happened. 

Anyway, looking forward to contributing some more to hopefully get Swift on par with Kotlin!

**Pull request closed without merging**
