### PR TITLE
derive custom path

### PR DESCRIPTION
**Pull request by geigerzaehler242**
Create extended keys using custom derivation paths

### CODE REVIEW

**Comment by reez** [comment]
Hey! @geigerzaehler242 do you have a few more of these PR's you have ready to submit? If you want to open PR's on all of them (but keep them separate PR's) I can review them all at once. 

Otherwise sometimes I miss that you submitted them, maybe this way I can just take a chunk of time to review all of the separate PR's at once that you have ready.

**Comment by geigerzaehler242** [comment]
i have one more "12.basic-transaction" that i will submit as soon as this current one gets merged

**Comment by reez** [comment]
> i have one more "12.basic-transaction" that i will submit as soon as this current one gets merged

Can you submit that PR too? That way I'll be able to review all of the outstanding separate PR's at the same time. Thanks!

**Comment by geigerzaehler242** [comment]
i think there will be a merge conflict with the readme which lists the individual scripts as i add them so that is why i'd like to keep them separate.

**Comment by thunderbiscuit** [comment]
Yeah you have two options here when you want to keep PRs separate that have a hierarchical dependency between each other:

1. You build a branch off of this one (the one for this PR), add your commits to it, and then open that branch as a PR (assume it would be PR 19). In the PR comments, you state that 18 needs to be merged first. These commits will then be added to master, and your PR 19 will become only the extra commits you added on top of this branch. The tradeoff there is that if this PR (18) requires changes and rebasing, you might need to do it on your other branch for PR 19 as well.
2. In this case the PRs don't have requirements between each other (no code from one depends on the other), and so your second option is to open them completely separately, and you are correct once one is merged, the one outstanding will have a small conflict in the readme. At that point you simply rebase that PR up to the latest on master, and you're good to go. This is also a fairly standard way to do this sort of thing.

Both options are commonly used, and the choice between them will depend on whether the code for your PRs have interdependencies or not. In this case they don't, so I'd recommend option 2. Matt is busy with a bunch of stuff and this sort of repo is very low priority given his expertise. I want to make sure we maximize his time well, and if he's asking to open all PRs at the same time to help him out let's do that.

You should also note that open PRs that are in the queue for weeks at a time (even months) before getting merged is very common. Don't feel discouraged if they do!

**Comment by geigerzaehler242** [comment]
btw this PR has been open a while. is the repo still active?

**Comment by reez** [comment]
ACK 640167075ea7ffcd93708632b39669fbe61cfe9e

**Pull request merged**
