### PR TITLE
9.private-descriptor-template.swift

### PR DESCRIPTION
**Pull request by geigerzaehler242**
Create private and public descriptors using descriptor templates.

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
How did the squashing go in PR 15?

**Comment by geigerzaehler242** [comment]
i closed it as i wanted to start clean from the master with my commits. going forward i will rebase if this same issue occurs where someone else merges a change to master before my branch has been merged.

**Comment by thunderbiscuit** [comment]
>i closed it as i wanted to start clean from the master with my commits.

This is not the correct way to be a good contributor to open source software.

As a maintainer of a few mid-size public repositories, I can tell you it's important that contributors know how to use the tools available to them and that all other developers use. You can read more about the burden of maintainership and how to be a good contributor in the awesome book _Working in Public: The Making and Maintenance of Open Source Software_.

I'm interested in merging your contributions of course, but moving forward don't close your PRs disregarding my advice and recommendations and simply refusing to learn the tools. This was the 4th time you closed a PR that absolutely did not need to be closed, it simply needed to be adjusted using the appropriate tools available to you, i.e. squashing, rebasing, force pushing, etc. Every new PR requires a new review and ACK from a knowledgeable Swift contributor that is not paid to do any of this.

And again if you are not familiar with the tools (and it's totally cool if you are not), most people, me included will be happy to help.

**Comment by geigerzaehler242** [comment]
ok thnx ill reach out when not familiar with one of the tools

**Review by reez — APPROVED** [review]
Reviewed and ran locally.

**Pull request merged**
