### PR TITLE
9.private descriptor template

### PR DESCRIPTION
**Pull request by geigerzaehler242**

### CODE REVIEW

**Comment by thunderbiscuit** [comment]
I think you might be creating more trouble for yourself by attempting to close and redo each PR. I like the contributions! Keep'em coming. But I also think knowing how to use git to its full potential will help you be a stronger contributor in the future. Do you mind picking up your PR #14 and continuing from there?

What you'll need is to reopen the PR. From there, we can see what needs to be done, but it's most likely a rebase. Have you done those before?

**Comment by geigerzaehler242** [comment]
i don't have permission to reopen the #14 pull request

**Comment by thunderbiscuit** [comment]
Ok sounds good. I can't reopen it for you so there might be something else we could do but I'm not sure what it is. 

Let's work off of this one. Our final goal is to have 1 commit, that sits right on top of the tip of the master branch, commit 114cb2493834cfeb6867cbfd0d9aa5d634ff46e1.

I think you'll need to do a few things:
1. Squash your 4 commits into 1
2. Rebase that onto master

### Part 1
Are you comfortable squashing? I think the best way to do this is to follow [this blog post](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) and do an interactive rebase. Are you using your command line to do this sort of stuff or do you rely on an IDE?

Once you've done your interactive rebase and you have 1 commit, your local branch and the branch on GitHub will differ, and a standard `git push` will get rejected. You'll need to use `git push --force`. Once you've done that we'll see it appear here and we can proceed to part 2. Let me know if you have any questions.

**Comment by geigerzaehler242** [comment]
I already pulled in all your master changes before making the #15 PR so isn't all that would be required now is to merge in my #15 commit?

**Comment by thunderbiscuit** [comment]
It would work indeed, but it's not optimal, and for the health of public and sizeable repositories commit history is important.

The reason for this is the following: you do have the correct changes, but your changes are not building off of master they instead merged back master into your branch. So if I merge this, I'm adding a messy commit history to the master branch that should not be there. Here the reason for this is that you have a merge commit from master to your branch, and you're attempting to merge that _back into master_. So overall it's just messy.

Instead, it's better to re-write history and simply pop your two original commits onto the master branch. This is a bit of work now that you've actually committed the merge, and so I propose to do it simpler: just squash all of your commits into one. From there the rebase will be easy, and then you'll have a super clean, 1-commit PR that sits on top of master. Easy merge.

**Pull request closed without merging**
