### PR TITLE
Create a Transaction object from raw bytes.

### PR DESCRIPTION
**Pull request by geigerzaehler242**
Create a Transaction object from raw bytes.

### CODE REVIEW

**Comment by geigerzaehler242** [comment]
done i think

**Comment by thunderbiscuit** [comment]
Hey not bad! I see you're trying stuff in the correct direction. Ok here is what it looks like right now:
commits

You now have 5 commits. Are you using an IDE to perform this, or your command line? I suggest you start with doing it on the command line, as that will show you the core of what is happening before using the fancy IDE tools.

What you want is a 2-step process:
1. Perform a `squash` on those 5 commits. The way to do this is by using an interactive rebase [read this article](). Your commit history (`git log --pretty=oneline --abbrev-commit`) currently looks something like this:
```sh
f6045c7 (HEAD -> create-tx-from-raw-bytes) Merge branch 'create-tx-from-raw-bytes' of https://github.com/geigerzaehler242/bitcoindevkit-scripts into create-tx-from-raw-bytes
50151d8 Combine all 3 commits into one
5dba782 Update 10.create-tx-from-raw-bytes.swift
445f86c Update 10.create-tx-from-raw-bytes.swift
cf6c35d Create a Transaction object from raw bytes.
d43f886 9.private-descriptor-template.swift
114cb24 (origin/master, master) Add Kotlin script 12: create a basic transaction
65b4bec Add Kotlin script 11: deriving extended keys at custom paths
732bf5d Update 8.transaction-details.swift
50e75cd 8.transaction-details
c8d6be6 Update 7.public-descriptor-template.swift
```
and you want the last 5 to be just 1. The command you'll need to start this process is 
```sh
git rebase --interactive cf6c35d
```
And from there choose `pick` or `reword` for the oldest commit and `squash` for the others, and follow along the tutorial I linked above.

You'll end up with 1 commit sitting on top of commit d43f8865c666605066a033fc8e701e12cb22bdbd. Try to push up to this PR; you'll see that it will fail with an error like "cannot push because branch cannot be fast-forwarded". At this point you'll need to force push. This will rewrite the history of this PR, and everything should be nice and clean.

Don't worry about making mistakes too much, we can just work on them one at a time. Just don't close this PR, and keep adding/hacking at it. You're definitely on the right path.

**Comment by geigerzaehler242** [comment]
i used the command line below, was prompted to squash/pick the commits as you indicated and did not use the IDE tools:

git rebase -i HEAD~3 

ill try again as per what you wrote above

**Comment by geigerzaehler242** [comment]
i did  the pick/squash but can't push/force since i am not on a branch?

 bitcoindevkit-scripts % git branch
* (no branch, rebasing create-tx-from-raw-bytes)
  9.private-descriptor-template.swift
  create-tx-from-raw-bytes
  master

**Comment by geigerzaehler242** [comment]
think i figured it out

**Review by thunderbiscuit — CHANGES_REQUESTED** [review]
Starting to look good!

Now you can squash those 2 commits you have in this PR into 1 and we'll be ready for the merge.

**Comment by geigerzaehler242** [comment]
aren't all the changes under one commit now or am i missing something?

**Comment by thunderbiscuit** [comment]
There are two ways you can tell this PR is attempting to merge 2 commits into the master branch:

1. The "Commits" tab at the top of the PR shows you that there are 2. If you click on it you'll get to see their hashes and commit messages.
tabs

2. If you look at the latest commit on the master branch you'll find it's the one with hash d43f8865c666605066a033fc8e701e12cb22bdbd. In your command line, make sure you're on your branch for the PR (called `create-tx-from-raw-bytes`) and type
```sh
git log --pretty=oneline --abbrev-commit
```
You'll find that there are two commits sitting on top of d43f8865c666605066a033fc8e701e12cb22bdbd. Your current PR is basically a proposal to merge both of those on my master branch. 

You can use the exact same process you used earlier to squash those two commits into one, force push, and we'll be good to go!

**Comment by geigerzaehler242** [comment]
7691622 (HEAD -> create-tx-from-raw-bytes, origin/create-tx-from-raw-bytes) Combine all 3 commits into one
cf6c35d Create a Transaction object from raw bytes.
d43f886 (upstream/master, upstream/HEAD) 9.private-descriptor-template.swift

**Comment by geigerzaehler242** [comment]
ok now it is one commit

**Review by thunderbiscuit — APPROVED** [review]
Looks good! Well done on the cleanups. ACK 0f99905a2daa904f8b4ee29c6bf315f3ed367825.

**Pull request merged**
